name: Ejecutar Script Automáticamente

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:        # Permite ejecutar el workflow manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Listar archivos en el directorio
        run: ls -la

      - name: Ejecutar el script
        run: python script.py

      - name: Enviar correo de notificación
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com          # Servidor SMTP (para Gmail)
          server_port: 587                        # Puerto SMTP
          username: ${{ jesus.tendicon@gmail.com }} # Usuario del email (correo)
          password: ${{ JesusAdrian;01 }} # Contraseña de aplicación
          subject: "Notificación de GitHub Actions"
          to: jesus.tendicon@gmail.com            # Correo del destinatario
          from: ${{ secrets.EMAIL_USERNAME }}     # Correo del remitente
          body: "El script se ejecutó correctamente en GitHub Actions."
