name: Ejecutar Script cada 5 Minutos

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias (si las hay)
        run: |
          pip install -r requirements.txt || echo "No hay dependencias"

      - name: Ejecutar el script
        run: python script.py
