name: Ejecutar Script cada 5 Minutos

on:
  workflow_dispatch:  # Esto permite la ejecución manual
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos (hora UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Ejecutar el script
        run: python script.py
